freelaway/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('auth/', include('authentication.urls')),
    path('jobs/', include('jobs.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from . import views


app_name = "jobs"

urlpatterns = [
    path('', views.Jobs.as_view(), name='list_jobs'),
    path('accept_job/<int:id>', views.accept_job, name='accept_job'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('send_project/', views.send_project, name='send_project'),
]

jobs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Reference(models.Model):
    file = models.FileField(upload_to="references/")

    def __str__(self):
        return self.file.url


class Job(models.Model):
    category_choices = (("D", "Design"), ("EV", "Edição de Video"))
    status_choices = (
        ("C", "Em criação"),
        ("AA", "Aguardando aprovação"),
        ("F", "Finalizado"),
    )

    title = models.CharField(max_length=200)
    description = models.TextField()
    category = models.CharField(
        max_length=2,
        choices=category_choices,
        default="D",
    )
    delivery_time = models.DateTimeField()
    price = models.FloatField()
    references = models.ManyToManyField(Reference)
    professional = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, blank=True)
    reserved = models.BooleanField(default=False)
    status = models.CharField(max_length=2, choices=status_choices, default="C")
    final_file = models.FileField(null=True, blank=True)
    
    def __str__(self):
        return self.title

jobs/views.py
from typing import Any
from django.http import HttpRequest

from django.shortcuts import render, redirect, get_object_or_404

from django.views.generic import View
from django.views.generic.list import ListView

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from utils import utils_accounts
from . import models

# Create your views here.
class Jobs(ListView):
    template_name = 'jobs/list_jobs.html'
    model = models.Job
    context_object_name = 'jobs'

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        super().setup(request, *args, **kwargs)
        self.user = request.user

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        query = super().get_queryset()
        query = query.filter(reserved=False)

        price_min = self.request.GET.get("price_min")
        if price_min:
            query = query.filter(price__gte=price_min) # Maior que,

        price_max = self.request.GET.get("price_max")
        if price_max:
            query = query.filter(price__lte=price_max) # Menor que,

        deadline_min = self.request.GET.get('deadline_min')
        if deadline_min:
            query = query.filter(delivery_time__gte=deadline_min) # Maior que,
        
        deadline_max = self.request.GET.get("deadline_max")
        if deadline_max:
            query = query.filter(delivery_time__lte=deadline_max) # Menor que,

        category = self.request.GET.get('category')
        if category:
            query = query.filter(category=category)

        return query


@login_required(redirect_field_name='login')
def accept_job(request, id):
    job = get_object_or_404(models.Job, id=id)
    job.professional = request.user
    job.reserved = True
    job.save()

    return redirect('jobs:list_jobs')


class Profile(View):
    template_name = 'jobs/profile.html'

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        super().setup(request, *args, **kwargs)
        if not self.request.user.is_authenticated:
            self.render_template = redirect('login')
        else:
            jobs = models.Job.objects.filter(professional=self.request.user)

            self.context = {
                'jobs': jobs,
            }
            self.render_template = render(
                self.request, self.template_name, self.context)
    
    def get(self, request, *args, **kwargs):
        return self.render_template
    
    def post(self, request, *args, **kwargs):
        errors = {}

        datas = request.POST
        username = datas.get('username')
        email = datas.get('email')
        first_name = datas.get("first_name")
        last_name = datas.get('last_name')

        errors.update(
            utils_accounts.check_username(username, request.user.username))

        if errors:
            messages.error(request, 'Ocorreu um erro')
        else:
            user = get_object_or_404(User, username=request.user.username)
            user.username = username
            user.email = email
            user.first_name = first_name
            user.last_name = last_name

            user.save()

        return redirect('jobs:profile')


def send_project(request):
    file = request.FILES.get('file')
    job_id = request.POST.get('job_id')

    job = get_object_or_404(models.Job, id=job_id)

    if job:
        job.final_file = file
        job.status = "AA"
        job.save()

    return redirect('jobs:profile')

jobs/templates/jobs/list_jobs.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'jobs/css/list_jobs.css' %}">
{% endblock %}


{% block body %}
  <div class="container">
    <br>
    <br>
    <div class="row">
      <div class="col-sm">
        <form action="{% url "jobs:list_jobs" %}" method="GET">
          <input type="text" class="form-control" placeholder="Preço mínimo" name="price_min">
          <br>
          <input type="text" class="form-control" placeholder="Preço máximo" name="price_max">
      </div>
          <div class="col-sm">
            <input type="date" class="form-control" name="deadline_min">
            <br>
            <input type="date" class="form-control" name="deadline_max">
          </div>
          <div class="col-sm">
            <select class="form-control" name="category">
              <option value="">Todos</option>
              <option value="D">Design</option>
              <option value="EV">Edição de vídeo</option>
            </select>
            <br>
            <input type="submit" class="btn btn-success btn-lg" value="FILTRAR">
        </form>
    </div>
  </div>
  <br>
  <br>
  <h2 class="titulo">JOB’S EM ABERTO:</h2>
  



    <div class="row justify-content-around">

      {% for job in jobs %}

        <div class="col-6 row-card">
          <div class="card-job">
            <div class="header-job">
              <h4 class="titulo-job">{{job.title}}</h4>
            </div>
            <div class="body-job">
              <p class="titulo-body">Descrição:</p>
              <div style="width: 70%">
                <p>{{job.description}}</p>
              </div>
              <div class="row">
                <div class="col-4">
                  <p class="titulo-body">Preço:</p>
                  <p>{{job.price}}</p>
                </div>
                <div class="col-4">
                  <p class="titulo-body">Prazo:</p>
                  <p>{{job.delivery_time}}</p>
                </div>
                <div class="col-4">
                  <p class="titulo-body">Categoria:</p>
                  <p>{% if job.category == 'D'%}
                      Design
                    {% else %}
                      Edição de vídeo
                    {% endif%}
                  </p>
                </div>
              </div>
              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-{{ job.id }}">Ver detalhes</button>

              <br>
              <br>
            </div>
          </div>
        </div>
        

        <div class="modal fade" id="modal-{{job.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div style="background-color: #333;" class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title job-modal-titulo" id="exampleModalLabel">JOB:</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                      <div>
                          <h4 class="titulo-job">{{job.title}}</h4>
                          
                          <h6 class="titulo-body">Descrição:</h6>
      
                          <p>{{job.description}}</p>
      
                          <div class="row">
      
                              <div class="col-4">
      
                                  <h6 class="titulo-body">Preço:</h6>
      
                                  <p>{{job.price}}</p>
      
                              </div>
      
                              <div class="col-4">
      
                                  <h6 class="titulo-body">Prazo:</h6>
      
                                  <p>{{job.delivery_time}}</p>
      
                              </div>
      
                              <div class="col-4">
      
                                  <h6 class="titulo-body">Categoria:</h6>
      
                                  <p>{{job.category}}</p>
      
                              </div>
      
                              
      
                          </div>
      
                          <h4 style="display:inline;" class="job-modal-titulo">Referencias:</h4>
                          <br>
                          <br>
                          <div class="row">
      
                              {% for reference in job.references.all %}
                              <div class="col-4">
                                  <img src="{{reference}}" width="100%"> 
                                  
      
                              </div>
                              {% endfor %}
      
                              
      
                          </div>
                          <br>
                          <br>
                          <a href="{% url 'jobs:accept_job' job.id %}" class="btn btn-success btn-lg">ACEITAR JOB</a>
      
                      </div>
                  </div>
              
              </div>
          </div>
      </div>
      {% endfor %}
    </div>
  </div>
        
{% endblock %}

jobs/templates/jobs/profile.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
		<link rel="stylesheet" href="{% static 'jobs/css/list_jobs.css' %}">
    <link rel="stylesheet" href="{% static 'jobs/css/profile.css' %}">
{% endblock %}


{% block body %}
    <br>
    <br>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{message.tags}}">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
        <div style="width: 60%">
            <form action="{% url 'jobs:profile' %}" method="POST">{% csrf_token %}
                <p>Username:</p>
                <input type="text" class="form-control" value="{{user.username}}" name="username">
                <br>
                <p>Email:</p>
                <input type="email" class="form-control" value="{{user.email}}" name="email">
                <br>
                <p>Primeiro nome:</p>
                <input type="text" class="form-control" value="{{user.first_name}}" name="first_name">
                <br>
                <p>Último nome:</p>
                <input type="text" class="form-control" value="{{user.last_name}}" name="last_name">
                <br>
                <input type="submit" class="btn btn-success btn-lg" value="Salvar alterações">
            </form>
        </div>
        <br>    
        <hr class="borda-degrade">
        <br>
        <h4 class="titulo">Histórico</h4>

        <table style="background-color: #222; color: white;" class="table table-striped">
            <thead>
                <tr>
                <th scope="col">Imagem</th>
                <th scope="col">Título</th>
                <th scope="col">Categoria</th>
                <th scope="col">Descrição</th>
                <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                  {% for job in jobs %}
                      <tr>
                          <th scope="row"><img width="100px" src="{{ job.references.all.0 }}"></th>
                          <td>{{ job.title }}</td>
                          <td>
                            {% if job.category == 'D' %}
                              Design
                            {% else %}
                              Edição de Video
                            {% endif %}
                          </td>
                          <td>{{ job.description }}</td>
                          <td>
                              {% if job.status == 'AA' %}
                                 <span class="badge badge-info">Aguardando aprovação</span>
                              {% elif job.status == 'C' %}
                                <button class="badge badge-primary" data-toggle="modal" data-target="#modal-job-{{job.id}}">Em criação</button>
                              {% else %}
                                  <span class="badge badge-success">Finalizado</span>
                              {% endif %}
                          </td>
                      </tr>
                  {% endfor %}
                </tr>
               
            </tbody>
        </table>

        {% for job in jobs %}
          {% if job.status == "C"%}
              <div class="modal fade" id="modal-job-{{ job.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                      <div style="background-color: #333;" class="modal-content">
                          <div class="modal-header">
                              <h5 style="font-size: 30px" class="modal-title titulo" id="exampleModalLabel">JOB:</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                              </button>
                          </div>

                          <div class="modal-body">
                              <h4 class="titulo-job">{{job.title}}</h4>
                              <br>
                              <h6 class="titulo-body">Status:</h6>

                              {% if job.status == 'AA'%}
                                <span class="badge badge-info">Aguardando aprovação</span>
                              {% elif job.status == 'C' %}
                                  <a class="badge badge-primary">Em criação</a>

                              {% else %}
                                  <span class="badge badge-success">Finalizado</span>
                              {% endif %}

                              <h6 class="titulo-body">Prazo máximo para entrega:</h6>
                              <p>{{job.delivery_time}}</p>

                              <hr style="border-color: yellow">
                              <form action="{% url 'jobs:send_project' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}

                                  <input type="file" class="form-control" placeholder="Enviar arquivos" name="file">
                                  <input type="hidden" name="job_id" value="{{ job.id }}">
                                  <br>
                                  <input type="submit" value="Enviar" class="btn btn-success btn-lg">
                              
                              </form>

                          </div>
                      
                      </div>
                  </div>
              </div>
          {% endif %}
      {% endfor %}

    </div>

{% endblock %}